### ISSUE TITLE
Cannot find module '@ntp.js/app'

### ISSUE THREAD

**Issue by GeorgeStratulat** [mobilpay/Node.js#2]
Salut! Mai este valabil codul? 
Daca da, am instalat cele 2 pachete externe si imi apare urmatoarea eroare la npm start din fisierul 'order.js'.
`Error: Cannot find module '@ntp.js/app'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    etc...`

Presupun ca de la aceasta linie: `var serviceManager = require( '@ntp.js/app' ).serviceManager;`
Ar trebui sa instalez un ntp service cumva?

**Comment by andreipanait** [comment]
Salut, este valabil si nu este necesara instalarea ntp, se pot seta direct valorile pentru signature si urls b92ad2f
